// app/src/routes/library/+page.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { savedKatas } from "$lib/library";
  import { listRuns, loadRun } from "$lib/api";
  import { statusForExit, isStreamEvent, type RunState, type RunRecord } from "$lib/events";
  import EventRow from "$lib/components/EventRow.svelte";
  import SummaryStat from "$lib/components/SummaryStat.svelte";
  import FilePlus from "@lucide/svelte/icons/file-plus";
  import FolderOpen from "@lucide/svelte/icons/folder-open";
  import Folder from "@lucide/svelte/icons/folder";
  import Search from "@lucide/svelte/icons/search";
  import Play from "@lucide/svelte/icons/play";
  import Package from "@lucide/svelte/icons/package";
  import GitBranch from "@lucide/svelte/icons/git-branch";
  import Hash from "@lucide/svelte/icons/hash";
  import Clock from "@lucide/svelte/icons/clock";
  import Coins from "@lucide/svelte/icons/coins";
  import Cpu from "@lucide/svelte/icons/cpu";
  import Terminal from "@lucide/svelte/icons/terminal";
  import CheckCircle from "@lucide/svelte/icons/check-circle";

  let runs = $state<RunRecord[]>([]);
  let detail = $state<Awaited<ReturnType<typeof loadRun>> | null>(null);
  let selRun = $state<string | null>(null);
  let selKata = $state<string | null>(null);

  // Fetch the run list once on mount. Using onMount (not $effect) makes the
  // mount-once intent explicit and keeps the fetch from being entangled with
  // any reactive read.
  onMount(async () => {
    const rs = await listRuns();
    runs = rs;
    if (selRun === null && rs.length > 0) selectRun(rs[0].id);
  });

  let run = $derived(detail?.record ?? null);
  let stream = $derived(detail ? detail.events.filter(isStreamEvent) : null);

  const stateOf = (r: RunRecord): RunState => statusForExit(r.exit ?? null);
  const tone = (s: RunState) => (s === "success" ? "success" : s === "warning" ? "warning" : "error");
  const statTone = (s: RunState) => (s === "success" ? "success" : s === "error" ? "error" : undefined);
  const fmtMs = (ms: number | null | undefined) => (ms == null ? "—" : `${(ms / 1000).toFixed(1)}s`);
  const fmtCost = (c: number | null | undefined) => (c == null ? "—" : `$${c.toFixed(3)}`);
  const fmtTurns = (t: number | null | undefined) => (t == null ? "—" : `${t}`);
  const fmtWhen = (secs: number) => {
    const d = new Date(secs * 1000);
    const hh = `${d.getHours()}`.padStart(2, "0");
    const mm = `${d.getMinutes()}`.padStart(2, "0");
    const startOfDay = (x: Date) => new Date(x.getFullYear(), x.getMonth(), x.getDate()).getTime();
    const days = Math.round((startOfDay(new Date()) - startOfDay(d)) / 86_400_000);
    const day = days === 0 ? "today" : days === 1 ? "yesterday"
      : days < 7 ? ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"][d.getDay()]
      : d.toLocaleDateString();
    return `${day} · ${hh}:${mm}`;
  };

  async function selectRun(id: string) {
    selRun = id;
    const r = runs.find((x) => x.id === id);
    if (r) selKata = r.kata;
    const loaded = await loadRun(id);
    // Guard against out-of-order responses: only apply if this is still the
    // selected run (rapid clicks can resolve loadRun calls in any order).
    if (selRun === id) detail = loaded;
  }
  function selectKata(name: string) {
    selKata = name;
    const latest = runs.find((r) => r.kata === name);
    if (latest) selectRun(latest.id);
    else { selRun = null; detail = null; }
  }
  const onKey = (fn: () => void) => (e: KeyboardEvent) => {
    if (e.key === "Enter" || e.key === " ") { e.preventDefault(); fn(); }
  };
</script>

<div class="wb">
  <header class="wb-toolbar">
    <div class="wb-brand"><span class="wb-seal">型</span></div>
    <div class="wb-sep"></div>
    <span style="font:var(--weight-semibold) var(--text-md)/1 var(--font-sans);color:var(--text-primary)">Library</span>
    <div class="wb-toolbar__spacer"></div>
    <div class="wb-toolbar__group">
      <button class="k-iconbtn" aria-label="Search"><Search size={16} /></button>
      <button class="k-iconbtn" aria-label="Open"><FolderOpen size={16} /></button>
    </div>
    <div class="wb-sep"></div>
    <a href="/" class="k-btn k-btn--secondary"><Play size={14} />Open Workbench</a>
  </header>

  <div class="wb-panes">
    <aside class="wb-pane wb-pane--rail">
      <div class="wb-rail__head"><span class="kata-eyebrow">Library</span></div>
      <div class="wb-rail__newbtn">
        <a href="/" class="k-btn k-btn--primary k-btn--block"><FilePlus size={14} />New kata<span class="k-kbd">Ctrl N</span></a>
      </div>
      <div class="wb-pane__body">
        <div class="wb-rail__section">
          <div class="wb-rail__label">Saved katas<span class="wb-rail__count">{savedKatas.length}</span></div>
          {#each savedKatas as k (k.name)}
            <div
              class="wb-kata"
              class:wb-kata--active={selKata === k.name}
              role="button"
              tabindex="0"
              onclick={() => selectKata(k.name)}
              onkeydown={onKey(() => selectKata(k.name))}
            >
              <div class="wb-kata__top">
                <span class="wb-kata__name">{k.name}</span>
                <span class="wb-kata__dot dot-{k.lastState}"></span>
              </div>
              <div class="wb-kata__desc">{k.description}</div>
              <div class="wb-kata__meta">
                {#if k.isolation === "worktree"}<span><GitBranch />worktree</span>{/if}
                <span><Package />{k.skills + k.plugins} kit</span>
                <span><Hash />{k.runs} runs</span>
              </div>
            </div>
          {/each}
        </div>
        <div class="wb-rail__section">
          <div class="wb-rail__label">Recent runs<span class="wb-rail__count">{runs.length}</span></div>
          {#each runs as r (r.id)}
            <div
              class="wb-hist"
              class:wb-hist--active={selRun === r.id}
              role="button"
              tabindex="0"
              onclick={() => selectRun(r.id)}
              onkeydown={onKey(() => selectRun(r.id))}
            >
              <span class="wb-hist__dot dot-{stateOf(r)}"></span>
              <div class="wb-hist__body">
                <span class="wb-hist__kata">{r.kata}</span>
                <span class="wb-hist__when">{fmtWhen(r.started_at)} · {fmtTurns(r.turns)} turns · {fmtCost(r.cost_usd)}</span>
              </div>
              <span class="k-badge k-badge--{tone(stateOf(r))}">exit {r.exit ?? "—"}</span>
            </div>
          {/each}
        </div>
      </div>
    </aside>

    {#if run}
      <div class="wb-detail">
        <div class="wb-detail__head">
          <div class="wb-detail__title">
            <h2>{run.kata}</h2>
            <span class="wb-detail__id">{run.id}</span>
            <div style="margin-left:auto">
              <span class="k-status k-status--{stateOf(run)}"><span class="k-status__dot"></span>exit {run.exit ?? "—"}</span>
            </div>
          </div>
          <div class="wb-detail__sub">
            <span><Clock />{fmtWhen(run.started_at)}</span>
            <span><Hash />{fmtTurns(run.turns)} turns</span>
            <span><Coins />{fmtCost(run.cost_usd)}</span>
            <span><Cpu />{fmtMs(run.duration_ms)}</span>
          </div>
          <div class="wb-detail__actions">
            <button class="k-btn k-btn--primary k-btn--sm"><Play size={13} />Re-run</button>
            <a href="/" class="k-btn k-btn--secondary k-btn--sm"><FolderOpen size={14} />Open in compose</a>
            <button class="k-btn k-btn--ghost k-btn--sm"><Package size={14} />Export bundle</button>
          </div>
        </div>
        <div class="wb-detail__body">
          <div class="wb-detail__stats">
            <SummaryStat label="EXIT" value={run.exit ?? "—"} tone={statTone(stateOf(run))} />
            <SummaryStat label="TURNS" value={fmtTurns(run.turns)} />
            <SummaryStat label="COST" value={fmtCost(run.cost_usd)} />
            <SummaryStat label="DURATION" value={fmtMs(run.duration_ms)} />
          </div>
          <div class="wb-detail__result">{run.result ?? ""}</div>
          <div>
            <div class="wb-detail__streamhead" style="margin-bottom:10px">Event log · {run.kata}</div>
            {#if stream}
              <div class="wb-detail__stream">
                {#each stream as ev, i (i)}<EventRow {ev} />{/each}
              </div>
            {:else}
              <div class="wb-detail__result" style="color:var(--text-faint)">Event log for this run has been pruned from local history.</div>
            {/if}
          </div>
        </div>
      </div>
    {:else}
      <div class="wb-detail" style="align-items:center;justify-content:center">
        <div class="wb-stream__empty">
          <Terminal size={28} />
          <p>Select a saved kata or a run from the rail to review its form and event log.</p>
        </div>
      </div>
    {/if}
  </div>

  <footer class="wb-statusbar">
    <span class="wb-statusbar__item wb-statusbar__ok">
      <CheckCircle size={13} /> {savedKatas.length} saved katas · {runs.length} runs in local history
    </span>
    <div class="wb-statusbar__spacer"></div>
    <span class="wb-statusbar__item"><Folder size={13} /> ~/.kata/runs</span>
  </footer>
</div>

// design/prototype/library.jsx
/* Kata Workbench — Layout C: saved-katas + run-history rail and the
   read-only run-detail view. Composes the design-system primitives. */
const LDS = window.KataDesignSystem_dd74c7;
const { Button, IconButton, Badge, StatusDot, SummaryStat, EventRow, Kbd } = LDS;
const LIcon = window.WBIcon;

function fmtMs(ms) { return (ms / 1000).toFixed(1) + "s"; }

/* ---------- Rail ---------- */
function KataRow({ k, active, onClick }) {
  return (
    <div className={"wb-kata" + (active ? " wb-kata--active" : "")} onClick={onClick}>
      <div className="wb-kata__top">
        <span className="wb-kata__name">{k.name}</span>
        <span className={"wb-kata__dot dot-" + k.lastState}></span>
      </div>
      <div className="wb-kata__desc">{k.description}</div>
      <div className="wb-kata__meta">
        {k.isolation === "worktree" && <span><LIcon name="git-branch" /> worktree</span>}
        <span><LIcon name="package" /> {k.skills + k.plugins} kit</span>
        <span><LIcon name="hash" /> {k.runs} runs</span>
      </div>
    </div>
  );
}

function HistRow({ r, active, onClick }) {
  const tone = r.state === "success" ? "success" : r.state === "warning" ? "warning" : "error";
  return (
    <div className={"wb-hist" + (active ? " wb-hist--active" : "")} onClick={onClick}>
      <span className={"wb-hist__dot dot-" + r.state}></span>
      <div className="wb-hist__body">
        <span className="wb-hist__kata">{r.kata}</span>
        <span className="wb-hist__when">{r.when} · {r.turns} turns · ${r.cost.toFixed(3)}</span>
      </div>
      <Badge tone={tone}>exit {r.exit}</Badge>
    </div>
  );
}

function Rail({ katas, history, selKata, selRun, onKata, onRun }) {
  return (
    <aside className="wb-pane wb-pane--rail">
      <div className="wb-rail__head"><span className="kata-eyebrow">Library</span></div>
      <div className="wb-rail__newbtn">
        <Button variant="primary" block icon={<LIcon name="file-plus" size={14} />}>New kata<Kbd>Ctrl N</Kbd></Button>
      </div>
      <div className="wb-pane__body">
        <div className="wb-rail__section">
          <div className="wb-rail__label">Saved katas<span className="wb-rail__count">{katas.length}</span></div>
          {katas.map((k) => (
            <KataRow key={k.name} k={k} active={selKata === k.name} onClick={() => onKata(k.name)} />
          ))}
        </div>
        <div className="wb-rail__section">
          <div className="wb-rail__label">Recent runs<span className="wb-rail__count">{history.length}</span></div>
          {history.map((r) => (
            <HistRow key={r.id} r={r} active={selRun === r.id} onClick={() => onRun(r.id)} />
          ))}
        </div>
      </div>
    </aside>
  );
}

/* ---------- Run detail ---------- */
function gutterFor(ev) {
  return ev.type === "assistant.text" ? "assistant"
    : ev.type === "tool.use" ? "tool"
    : ev.type === "tool.result" ? "result"
    : ev.type === "turn" ? `turn ${ev.n}` : "log";
}
function variantFor(ev) {
  return ev.type === "assistant.text" ? "assistant"
    : ev.type === "tool.use" ? "tooluse"
    : ev.type === "tool.result" ? (ev.ok ? "result-ok" : "result-err")
    : ev.type === "turn" ? "turn" : "log";
}

function RunDetail({ run, stream }) {
  if (!run) {
    return (
      <div className="wb-detail" style={{ alignItems: "center", justifyContent: "center" }}>
        <div className="wb-stream__empty">
          <LIcon name="terminal" size={28} />
          <p>Select a saved kata or a run from the rail to review its form and event log.</p>
        </div>
      </div>
    );
  }
  const tone = run.state === "success" ? "success" : run.state === "warning" ? "warning" : "error";
  return (
    <div className="wb-detail">
      <div className="wb-detail__head">
        <div className="wb-detail__title">
          <h2>{run.kata}</h2>
          <span className="wb-detail__id">{run.id}</span>
          <div style={{ marginLeft: "auto" }}><StatusDot state={run.state} label={`exit ${run.exit}`} /></div>
        </div>
        <div className="wb-detail__sub">
          <span><LIcon name="clock" /> {run.when}</span>
          <span><LIcon name="hash" /> {run.turns} turns</span>
          <span><LIcon name="coins" /> ${run.cost.toFixed(3)}</span>
          <span><LIcon name="cpu" /> {fmtMs(run.ms)}</span>
        </div>
        <div className="wb-detail__actions">
          <Button variant="primary" size="sm" icon={<LIcon name="play" size={13} />}>Re-run</Button>
          <Button variant="secondary" size="sm" icon={<LIcon name="folder-open" size={14} />}>Open in compose</Button>
          <Button variant="ghost" size="sm" icon={<LIcon name="package" size={14} />}>Export bundle</Button>
        </div>
      </div>
      <div className="wb-detail__body">
        <div className="wb-detail__stats">
          <SummaryStat label="EXIT" value={run.exit} tone={run.state === "success" ? "success" : run.state === "error" ? "error" : undefined} />
          <SummaryStat label="TURNS" value={run.turns} />
          <SummaryStat label="COST" value={`$${run.cost.toFixed(3)}`} />
          <SummaryStat label="DURATION" value={fmtMs(run.ms)} />
        </div>
        <div className="wb-detail__result">{run.result}</div>
        <div>
          <div className="wb-detail__streamhead" style={{ marginBottom: "10px" }}>Event log · {run.kata}</div>
          {stream ? (
            <div className="wb-detail__stream">
              {stream.map((ev, i) => (
                <EventRow key={i} variant={variantFor(ev)} gutter={gutterFor(ev)}
                  tool={(ev.type === "tool.use" || ev.type === "tool.result") ? ev.name : null}>
                  {ev.type === "assistant.text" ? ev.text
                    : ev.type === "tool.use" ? ev.input_summary
                    : ev.type === "tool.result" ? ev.summary
                    : ev.type === "log" ? ev.message
                    : ev.type === "turn" ? <span style={{ display: "block", borderTop: "1px dashed var(--border-subtle)", marginTop: "6px" }}></span>
                    : ""}
                </EventRow>
              ))}
            </div>
          ) : (
            <div className="wb-detail__result" style={{ color: "var(--text-faint)" }}>Event log for this run has been pruned from local history.</div>
          )}
        </div>
      </div>
    </div>
  );
}

/* ---------- Library screen ---------- */
function Library() {
  const { savedKatas, history, streams } = window.WBLibrary;
  const [selRun, setSelRun] = React.useState(history[0].id);
  const [selKata, setSelKata] = React.useState(history[0].kata);

  const run = history.find((r) => r.id === selRun) || null;

  function onRun(id) {
    setSelRun(id);
    const r = history.find((x) => x.id === id);
    if (r) setSelKata(r.kata);
  }
  function onKata(name) {
    setSelKata(name);
    const latest = history.find((r) => r.kata === name);
    setSelRun(latest ? latest.id : null);
  }

  return (
    <div className="wb">
      <header className="wb-toolbar">
        <div className="wb-brand"><span className="wb-seal">型</span></div>
        <div className="wb-sep"></div>
        <span style={{ font: "var(--weight-semibold) var(--text-md)/1 var(--font-sans)", color: "var(--text-primary)" }}>Library</span>
        <div className="wb-toolbar__spacer"></div>
        <div className="wb-toolbar__group">
          <IconButton icon={<LIcon name="search" />} aria-label="Search" />
          <IconButton icon={<LIcon name="folder-open" />} aria-label="Open" />
        </div>
        <div className="wb-sep"></div>
        <Button variant="secondary" icon={<LIcon name="play" size={14} />}>Open Workbench</Button>
      </header>
      <div className="wb-panes">
        <Rail katas={savedKatas} history={history} selKata={selKata} selRun={selRun} onKata={onKata} onRun={onRun} />
        <RunDetail run={run} stream={run ? streams[run.id] : null} />
      </div>
      <footer className="wb-statusbar">
        <span className="wb-statusbar__item wb-statusbar__ok"><LIcon name="check-circle" /> {savedKatas.length} saved katas · {history.length} runs in local history</span>
        <div className="wb-statusbar__spacer"></div>
        <span className="wb-statusbar__item"><LIcon name="folder" /> ~/.kata/history</span>
      </footer>
    </div>
  );
}

ReactDOM.createRoot(document.getElementById("root")).render(<Library />);
